name: CI
on: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Configure Python version
        uses: actions/setup-python@v5

      - name: Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
