name: CI
on: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Configure Python version
        uses: actions/setup-python@v6

      - name: Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
